services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - crawler_test

  db:
    image: mysql
    restart: always
    hostname: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - crawler_test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - crawler_test

networks:
  crawler_test:
    driver: bridge
